### ISSUE TITLE
Strange URLs when activating (bunny.net)

### ISSUE THREAD

**Issue by VilterPD** [somehow-digital/typo3-media-processing#12]
Hi dear developers,

the extension is producing strange URLS for me when I activate it, leading to 404 errors for the images:

src="https://cdn.dev.trauminselreisen.de/https:/www.dev.trauminselreisen.de/fileadmin/templates/images/Platzhalter-Bilder/Trauminsel_Reisen_Bedienelemente_8._Reisethemen_2.jpg?width=640"

The origin URL is strangely nested inside. The actual URL should be
src="https://cdn.dev.trauminselreisen.de/fileadmin/templates/images/Platzhalter-Bilder/Trauminsel_Reisen_Bedienelemente_8._Reisethemen_2.jpg?width=640"

Which would work. I have also appended the settings I have set, though they are not very numerous

![Screenshot 2024-06-06 at 16-04-27 Install Tool on site Trauminselreisen · Trauminselreisen TYPO3 CMS 12 4 10](https://github.com/somehow-digital/typo3-media-processing/assets/59023174/eade6b00-ca88-4345-9d70-34cba8a22a65)
![Screenshot 2024-06-06 at 16-04-35 Install Tool on site Trauminselreisen · Trauminselreisen TYPO3 CMS 12 4 10](https://github.com/somehow-digital/typo3-media-processing/assets/59023174/7304465e-79fd-48d8-9807-eac45b6361c1)

**Comment by thasmo** [comment]
I can't test this right now, but I'd assume the problem occurs somewhere in https://github.com/somehow-digital/typo3-media-processing/blob/main/Classes/UriBuilder/BunnyUriSource.php

**Comment by thasmo** [comment]
@VilterPD, what happens when you set `https://cdn.dev.trauminselreisen.de/` as api_endpoint (Pull Zone URL)?

**Comment by thasmo** [comment]
@VilterPD, the issue seems to be related to setting `config.absRefPrefix` to some value other than `auto` or`/`, so most likely you're using `config.absRefPrefix` with a custom domain value. If you can remove this for now, it should prevent the issue.

But this needs a fix on our side.

**Comment by VilterPD** [comment]
> @VilterPD, what happens when you set `https://cdn.dev.trauminselreisen.de/` as api_endpoint (Pull Zone URL)?

I get another strange URL

https://cdn.dev.trauminselreisen.de/https:/www.dev.trauminselreisen.de/fileadmin/user_upload/CLI_-_Peninsula_Villa_-_Aerial_6_Trauminsel_Reisen.jpg?width=2048&height=934

**Comment by VilterPD** [comment]
> @VilterPD, the issue seems to be related to setting [`config.absRefPrefix`](https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/TopLevelObjects/Config.html#confval-config-absrefprefix) to some value other than `auto` or `/`, so most likely you're using `config.absRefPrefix` with a custom domain value. If you can remove this for now, it should prevent the issue.
> 
> But this needs a fix on our side.

Ill try changing it

**Comment by thasmo** [comment]
Version 0.5.0 has a fix for this. Thank you for reporting the issue! :)

**Comment by VilterPD** [comment]
Oh, nice, thanks. Sadly I don't really have access to the parameter directly, but I have asked the other developer to change it to auto. Thanks

**Comment by thasmo** [comment]
> Oh, nice, thanks. Sadly I don't really have access to the parameter directly, but I have asked the other developer to change it to auto. Thanks

FYI: With version 0.5.0 you don't even need to change `absRefPrefix`.
