### ISSUE TITLE
Invalid crop options in ImgProxyUri

### ISSUE THREAD

**Issue by rtp-cgs** [somehow-digital/typo3-media-processing#14]
When one of the gravity values in the crop options is 0 it will result in a invalid crop option.

This:
Classes/ImageService/ImgProxyImageService.php:118
->setCrop(1920, 698, [583, 0])

Results in this, which is invalid because if the gravity is set there always has to be am x  & y value.
https://imgproxy.tld/.../c:1920:698:nowe:583/...

**Comment by thasmo** [comment]
Thanks! The issue was also present and fixed on the Optimole integration. 👍
