### ISSUE TITLE
PDF preview image missing in file selector 

### ISSUE THREAD

**Issue by rtp-cgs** [somehow-digital/typo3-media-processing#17]
The PDF preview images are missing in the file selector.

![CleanShot 2024-08-08 at 16 08 06](https://github.com/user-attachments/assets/ef08faab-7780-47a2-87c9-cd3f3259717f)

**Comment by thasmo** [comment]
Your PR suggests that the underlying issue is that TYPO3 does not supply the dimensions for the PDF document. Is that correct? Do we know why this is? Should TYPO3 actually supply the dimensions in the first place?

**Comment by thasmo** [comment]
Wondering if we should "just" add some post-uploading event handler and using something like https://github.com/smalot/pdfparser to persist correct dimensions in the `sys_file` table.

**Comment by thasmo** [comment]
I'm going to fix this via several changes:

* Skip processing for files which have no dimensions defined.
* Implement a solution to set dimensions of PDF files.
* Add configuration option for `ImgProxy` to handle PDF files, which is a PRO feature.

**Comment by rtp-cgs** [comment]
Maybe this could help to get the filesizes:
https://docs.imgproxy.net/usage/getting_info

**Comment by thasmo** [comment]
I've fixed the issue by [determining PDF dimension](https://github.com/somehow-digital/typo3-media-processing/commit/42c04b8f2186202dbe3a0f5d588919e211335429)s prior to processing.
