### ISSUE TITLE
Missing composer dependency

### ISSUE THREAD

**Issue by rtp-cgs** [somehow-digital/typo3-media-processing#20]
Please add this to the composer dependencies this can otherwise lead to errors due to missing classes.

"typo3/cms-reports": "^12.4"

**Comment by thasmo** [comment]
This was a service configuration issue and has been [resolved](https://github.com/somehow-digital/typo3-media-processing/commit/80c2e966e0cf45716a58d6760646d02da392434a). Thanks for reporting, really appreciate it! :)

**Comment by rtp-cgs** [comment]
I think there should still be a requirement in composer.json since you can run a typo3 instance without the typo3/cms-reports package if you want.

**Comment by thasmo** [comment]
> I think there should still be a requirement in composer.json since you can run a typo3 instance without the typo3/cms-reports package if you want.

I thought so, too, at first. But when I add `typo3/cms-reports` as a dependency, it will also install the extension in the TYPO3 backend and will also show it in the navigation. Also, some official TYPO3 packages, which include custom reports, do not define it as a requirement. Normally I'd define this as a required package, as I am using some classes and interfaces from the `typo3/cms-reports` package, but doing so - as mentioned - also installs the module in the backend, which is not what I want for obvious reasons.
