### ISSUE TITLE
Not invalidating files when file location changed

### ISSUE THREAD

**Issue by tmhf** [somehow-digital/typo3-media-processing#24]
When you move a file to a different directory, or move the whole directory in the TYPO3 backend, the processed files of the affected files should be invalidated in the database.

Replicate this by loading a file in the frontend, then moving it to another directory and reload the page. The image url still points to the old location and therefor it's not loading the image.

**Comment by thasmo** [comment]
Indeed. Thanks for reporting!

**Comment by thasmo** [comment]
@tmhf, this was fixed and released with version v0.7.1. Thanks again for reporting! :)
