### ISSUE TITLE
Advanced cropping with custom focus point on imagekit

### ISSUE THREAD

**Issue by fgerards** [somehow-digital/typo3-media-processing#6]
Another aspect that struck me while trying out the extension with imagekit.io:

if you have a custom focus point / crop-area and want imagekit.io to do the transformation, you have to deliver the custom crop area coordinates via the API in a POST payload. Also, you have to prefix the transformation parameters in zhe URL segment (the default communication method of the extension) with „tr:“

**Comment by thasmo** [comment]
Indeed, I'm not sure what I did when implementing this. 😅

This is fixed and will be released with version `0.3.2` soon.
(On top, URL signing for imagekit.io was also added. 🥳)

**Comment by thasmo** [comment]
Version `0.3.2` has been released and contains a fix for this.

**Comment by fgerards** [comment]
hi, you already did an awesome job releasing this extension, thx for that :). As many clients on bigger websites ask for CDN and fast image processing. I will try out the 0.3.2 and give you feedback :)

**Comment by thasmo** [comment]
@fgerards, thanks! :)

Feel free to keep giving feedback, really appreciate it!

**Comment by fgerards** [comment]
btw., i also tested it in V11.5 (with php 8.1) and i dont know this is v11 related: if you choose a category name with a dot in it in ext_conf_template.txt (like # cat=imagekit.io), then the tab in the "settings" module is empty

**Comment by thasmo** [comment]
> i tested it and a signed url produced by 0.3.2 now is https://ik.imagekit.io/voc6qgmbnw/tr:cm-extract,w-1994,h-660,x-2,y-154:c-at_max,w-870,h-//fileadmin/Allgemeines_Bildmaterial/Header_Bilder/Header_baramundi_UEM.png?ik-t=1716897858&ik-s=97e0a5424534ee2c00f2139ec5b815a862e98690 - it seems like duplicate "w" and "h" attribute (the doubleslash results in my source path simply being "/").

Attributes are fine in this case as they do refer to different operations. The first operation (`cm-extract,w-1994,h-660,x-2,y-154`) defines image cropping of the original image, the second operation (`c-at_max,w-870`) defines image scaling/sizing of the cropped image - it is a transformation chain.

For the double slash; the value of `Origin Host URL (`imagekit.io.integration.imagekit.source_uri [string]`) should be the complete hostname URL or left empty, which will set the hsotname to the request hostname. It is not intended to be set to a slash (`/`).

In the future it would be nice to validate the settings' values and have a better documentation for them as well.

Btw. I've commited a change which should get rid of the empty `h-` parameter in a future release.

Thanks!

**Comment by thasmo** [comment]
In addition I've commited a change which will trim leading/trailing slashes from the source URL, so this should at least enable your use case for now. Release still pending.

**Comment by thasmo** [comment]
@fgerards, version `0.3.3` has been released and should fix the issues you mentioned.

**Comment by fgerards** [comment]
thx all lot - all working as promised :D
