### ISSUE TITLE
Focuspoint options for imgproxy service

### ISSUE THREAD

**Issue by rtp-cgs** [somehow-digital/typo3-media-processing#9]
We would like the imgproxy service to respect the focuspoints selected in the TYPO3 backend.
If adding this to your extension I would provide an pull request for this feature.

**Comment by thasmo** [comment]
Of course, please go ahead! 🙂

**Comment by thasmo** [comment]
@rtp-cgs, thanks again for your contribution. I've released [v0.4.0](https://github.com/somehow-digital/typo3-media-processing/releases/tag/v0.4.0) incorporating your contributed feature!

**Comment by thasmo** [comment]
Hey @rtp-cgs! Recently, I've taken a closer look at the `focusArea` option in TYPO3 and realized that it "just" defines an area within the crop area for the user in the backend, and it isn't necessarily meant to be used as a primary area for cropping the image.

What is your use case here, or how do you use the `focusArea` with imgproxy? Thanks!

**Comment by thasmo** [comment]
I just realized; are you actually refering to https://extensions.typo3.org/extension/focuspoint ? :D

**Comment by thasmo** [comment]
Well, maybe not. I guess I just don't really know what imgproxy does with the gravity:fp option. :D

**Comment by thasmo** [comment]
@rtp-cgs, anyway. Does the feature work as you want it to? Thank you!

**Comment by rtp-cgs** [comment]
Hello @thasmo 

Yes the core does only define a focus area in the backend the frontend implementation is left open.
We solve it with a custom image viewhelper which passes down the focusArea to as processing instructions.

Yes the feature works perfectly fine for us.
